# -*- mode: ruby -*-
# vi: set ft=ruby :

# See README.md for details

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.box = "bento/centos-6.7"

  config.vm.define "puppetmaster" do |puppetmaster|
  
    puppetmaster.vm.hostname = "puppetmaster.nexperience.com"
  
    puppetmaster.vm.network "private_network", ip: "172.31.0.201"
  
  end
  
end
